# Generated by Django 4.0.5 on 2022-08-04 09:12

from django.db import migrations, models
import django.db.models.deletion
import my_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mongo_id', models.CharField(default='CONTINENTMONGOID', max_length=300)),
                ('event_id', models.CharField(default='EVENTMONGOID', max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country_code', models.CharField(default='000', max_length=5)),
                ('country_short', models.CharField(default='IIII', max_length=6)),
                ('mongo_id', models.CharField(default='COUNTRYMONGOID', max_length=300)),
                ('event_id', models.CharField(default='EVENTMONGOID', max_length=300)),
                ('continent', models.ForeignKey(default=my_api.models.Continent.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='my_api.continent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('lat_lon', models.CharField(default='DefaultName', max_length=600)),
                ('city_code', models.CharField(default='CITY', max_length=25)),
                ('city_area', models.CharField(default='000', max_length=25)),
                ('mongo_id', models.CharField(default='REGIONMONGOID', max_length=300)),
                ('event_id', models.CharField(default='EVENTMONGOID', max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='RequestsRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.TextField(default='Default')),
                ('url_req', models.TextField(default='Default')),
                ('response', models.TextField(default='Default')),
                ('username', models.TextField(default='Default')),
                ('session_id', models.TextField(default='Default')),
                ('date_time_rec', models.CharField(default='None', max_length=500)),
                ('mongo_id', models.CharField(default='REQMONGOID', max_length=300)),
                ('event_id', models.CharField(default='REQEVENTID', max_length=300)),
                ('time_z', models.CharField(default='Africa/Abidjan', max_length=300)),
                ('project_code', models.CharField(default='None', max_length=300)),
                ('is_success', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZoneDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_attained', models.CharField(max_length=300)),
                ('timezone_attained', models.CharField(max_length=300)),
                ('country_attained', models.CharField(max_length=300)),
                ('city_attained', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mongo_id', models.CharField(default='SUBREGIONMONGOID', max_length=300)),
                ('event_id', models.CharField(default='EVENTMONGOID', max_length=300)),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.regions')),
            ],
        ),
    ]
