# Generated by Django 4.0.5 on 2023-09-11 05:47

from django.db import migrations, models
import django.db.models.deletion
import my_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('lat_lon', models.CharField(default='DefaultLatLon', max_length=600)),
                ('lat', models.CharField(default='DefaultLat', max_length=600)),
                ('lon', models.CharField(default='DefaultLon', max_length=600)),
                ('city_code', models.CharField(default='CITY', max_length=25)),
                ('city_area', models.CharField(default='000', max_length=25)),
                ('mongo_id', models.CharField(default='REGIONMONGOID', max_length=300)),
                ('event_id', models.CharField(default='EVENTMONGOID', max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Countries2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country_code', models.CharField(default='000', max_length=5)),
                ('country_short', models.CharField(default='IIII', max_length=6)),
                ('mongo_id', models.CharField(default='COUNTRYMONGOID', max_length=300)),
                ('event_id', models.CharField(default='EVENTMONGOID', max_length=300)),
                ('continent', models.ForeignKey(default=my_api.models.Continent.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='my_api.continent')),
            ],
        ),
    ]
