# Generated by Django 4.0.5 on 2023-09-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_regions2_countries2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions2',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.countries2'),
        ),
    ]
