# Generated by Django 4.0.5 on 2022-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_countries_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='country_short',
            field=models.CharField(default='IIII', max_length=6),
        ),
    ]
